### ISSUE TITLE
Additional Plotting Libraries

### ISSUE THREAD

**Issue by KobaKhit** [eskin22/upsetty#1]
Hello. Saw your post on reddit. Love this idea. Are you set on using plotly as the exclusive plotting backend for this project? Would you consider adding support for https://github.com/altair-viz/altair ? I recreated the upset chart in altair and could make a pull request.

**Comment by eskin22** [comment]
Hi there! Thank you for taking an interest in upsetty. I have never used Altair before but I'm completely open to the idea. If you'd like to try to integrate it and create a pull request, please feel welcome to do so. :)
